apiVersion: apps/v1
kind: Deployment
metadata:
  name: jogo-da-vida-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jogo-da-vida
  template:
    metadata:
      labels:
        app: jogo-da-vida
    spec:
      containers:
      - name: server
        image: <SEU_USUARIO_DOCKERHUB>/jogo-da-vida:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: jogo-da-vida-service
spec:
  type: NodePort
  selector:
    app: jogo-da-vida
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007 