apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jogo-da-vida-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jogo-da-vida-server
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 